### PR TITLE
Added test case for github issue 1775

### PR DESCRIPTION
**Pull request by pascal-hofmann**
I finally managed to create a test case for #1775.

### CODE REVIEW

**Comment by malarzm** [comment]
@pascal-hofmann is the test also failing on 1.2.x branch?

**Comment by pascal-hofmann** [comment]
@malarzm Yes. I only used 1.1.x because that's what's in use here. Should I create a PR for 1.2.x?

**Comment by malarzm** [comment]
No need, just wanted to make sure it's not something that was fixed "in the meantime" :)

**Comment by alcaeus** [comment]
Closing here, the test is part of #1784. Thanks!

**Pull request closed without merging**
