### PR TITLE
Add alternative to deprecated annotations

### PR DESCRIPTION
**Pull request by j0k3r**
Following discussion from https://github.com/doctrine/mongodb-odm/issues/1459#issuecomment-255722659
Instead of just saying that this class is deprecated (and probably got a lot of issues related to that) add an alternative to it.

### CODE REVIEW

**Comment by j0k3r** [comment]
@alcaeus should be ok now.

**Comment by alcaeus** [comment]
Awesome, thanks! 🍻

**Comment by malarzm** [comment]
Ah, forgot one can now change target branch of PR, approved changes and left for evening to merge manually :baby:

**Comment by j0k3r** [comment]
👍

**Pull request merged**
