### PR TITLE
doc: Remove soft-delete-cookbook

### PR DESCRIPTION
**Pull request by GromNaN**
|      Q       |   A
|------------- | -----------
| Type         | doc
| BC Break     | no
| Fixed issues | -

#### Summary

The repository have been archived: https://github.com/doctrine/mongodb-odm-softdelete

### CODE REVIEW

**Review by alcaeus — APPROVED** [review]
Does this count as soft-delete since it's still available in git history? 🤔

**Comment by GromNaN** [comment]
It looks like we can rewrite this cookbook with doctrine extensions: https://github.com/doctrine-extensions/DoctrineExtensions/blob/main/src/SoftDeleteable/Mapping/Event/Adapter/ODM.php

**Review by SenseException — APPROVED** [review]
Was this a remnant of something older? I can't find a link that is directing to the removed file. :thinking:

**Comment by GromNaN** [comment]
> Was this a remnant of something older? I can't find a link that is directing to the removed file. 🤔

The sidebar has an automatic listing of all cookbooks: https://github.com/doctrine/mongodb-odm/blob/8b542f4c5b9239a3083a375894c4249e922b315d/docs/en/sidebar.rst?plain=1#L63

**Pull request merged**
