### PR TITLE
Add PHP 7 on Travis

### PR DESCRIPTION
**Pull request by Soullivaneuh**
On allowed failures section as unstable version.

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
ping

**Comment by malarzm** [comment]
Right now there is no point in adding this to travis matrix given we're not supporting new Mongo driver yet.

**Comment by Soullivaneuh** [comment]
> we're not supporting new Mongo driver yet.

Did you plan something about it? Any WIP PR?

**Comment by malarzm** [comment]
Yes, we have plans for it, no there's no WIP PR yet unfortunately :(

**Comment by Soullivaneuh** [comment]
And what it your plans? Can I help? :-)

**Comment by jmikola** [comment]
An initial task (possible today) would be getting [doctrine/mongodb](https://github.com/doctrine/mongodb) and [ODM](https://github.com/doctrine/mongodb-odm) working on [mongofill](https://github.com/mongofill/mongofill). That would grant us PHP 7 and HHVM support in one shot, as was done in the [Bernhard project](https://github.com/bernardphp/bernard/blob/master/tests/travis.sh). It shouldn't require more than some Travis CI modifications, as mongofill is designed to be a drop-in replacement for the legacy driver.

The more ambitious and long-term initiative is to port things over to the new [PHP driver](https://github.com/mongodb/mongo-php-driver), which will be getting PHP 7 support in a forthcoming release (see mongodb/mongo-php-driver/pull/136). There is also an HHVM version of this new driver, which shares the very same API.

**Comment by Soullivaneuh** [comment]
Ok I see, thanks for the explanation.

I think the first solution should be implemented quickly on a new minor to allow legacy projects to run on PHP7.

In this case, you will have indeed more time to decide the future of your odm. :+1:

**Comment by alcaeus** [comment]
Going to close this as PHP 7 support is not going to be possible for quite some time due to the new driver API.

**Pull request closed without merging**
