### PR TITLE
Findonebywithsort

### PR DESCRIPTION
**Pull request by nottoohigh**
|      Q       |   A
|------------- | -----------
| Type         |feature
| BC Break     | no
| Fixed issues | #2226

#### Summary

Added `$sort` param to `Doctrine\ODM\MongoDB\Repository\DocumentRepository::findOneBy` with test.

### CODE REVIEW

**Review by malarzm — APPROVED** [review]
Thank you for the PR, the code looks good! Could you please squash your commits into one so we can merge? Also it seems that the commits are not associated with your account. Is this intentional?

**Comment by nottoohigh** [comment]
> Thank you for the PR, the code looks good! Could you please squash your commits into one so we can merge? Also it seems that the commits are not associated with your account. Is this intentional?

Hi, I tried to rectify as requested, and made a new commit but it seems the Travis CI is failing now. I didn't actually change any code on my side, just squashed commits and pushed. Is the Travis CI issue something that I need to or can address? Thanks!

**Comment by malarzm** [comment]
@nottoohigh don't worry about the Travis, same failure is happening on other branches and we'll address it later. Something went wrong with the rebase though as now there are 6 commits - we need 1. If you'll have troubles with that let me know, I'll make the rebase later on my own.

**Comment by nottoohigh** [comment]
@malarzm yes thank you if you can do the rebase I would appreciate it. I might inadvertently make it worse if I attempt another one (9 commits maybe!). Thanks again!

**Comment by malarzm** [comment]
@nottoohigh I have rebased and squashed your commits in #2264. Thank you very much for the feature!

**Pull request closed without merging**
