### PR TITLE
Update phpunit

### PR DESCRIPTION
**Pull request by malarzm**
As per title. For now I've decided to use https://packagist.org/packages/dms/phpunit-arraysubset-asserts as it's easier than changing test for views :)

### CODE REVIEW

**Comment by malarzm** [comment]
@alcaeus we need to either drop PHP 7.2 or postpone this update to 2.2

**Comment by alcaeus** [comment]
Dropping 7.2 is out of the question for now. We can change the constraint to `^8.2 || ^9.0`.

**Comment by malarzm** [comment]
I'll see what needs to happen with array subsets. It's not critical for 2.1 so I'll take it off the roadmap

**Comment by alcaeus** [comment]
Taken care of in #2248.

**Pull request closed without merging**
