### PR TITLE
Update doctrine/coding-standard

### PR DESCRIPTION
**Pull request by malarzm**
|      Q       |   A
|------------- | -----------
| Type         | improvement
| BC Break     | no
| Fixed issues | n/a

### CODE REVIEW

**Comment by malarzm** [comment]
@alcaeus if you prefer I may remove all the whitespace changes to a separate PR (sadly I thought about this too late in the progress)

**Comment by alcaeus** [comment]
> @alcaeus if you prefer I may remove all the whitespace changes to a separate PR (sadly I thought about this too late in the progress)

Assuming the changes were made by running `vendor/bin/phpcbf`, I'm not going to review this PR beyond the phpcs.xml file ;)

**Comment by malarzm** [comment]
Ok I'll need to split it then as there were few manual changes

**Comment by alcaeus** [comment]
Separate commits will do 😊

**Review by alcaeus — APPROVED** [review]
Changes in src look good, didn't bother with tests.

**Comment by malarzm** [comment]
Thanks! I'll be making follow-up PRs prolly today

**Pull request merged**
