### PR TITLE
Lock document only if found

### PR DESCRIPTION
**Pull request by notrix**
I have issue that some documents expire in mongodb and references return null.
Then $repository->find($invalidId, LockMode::OPTIMISTIC); throws exceptions when UnitOfWork tries to lock NULL.

### CODE REVIEW

**Comment by jwage** [comment]
:+1:

**Comment by jwage** [comment]
Thanks for the fix!

**Comment by men232** [comment]
What about setLockMode in Doctrine\ODM\MongoDB\Query\Query like Doctrine\ORM\Query?

**Comment by malarzm** [comment]
@men232 feel free to open new issue or submit a PR implementing that :)

**Pull request merged**
