### PR TITLE
Add missing parent::configure() call

### PR DESCRIPTION
**Pull request by theyough**
|      Q       |   A
|------------- | -----------
| Type         | bug
| BC Break     | yes/no
| Fixed issues | doctrine/DoctrineMongoDBBundle#639

#### Summary

see issue details

### CODE REVIEW

**Comment by malarzm** [comment]
@theyough thank you for the PR? Would you mind targeting the 1.3.x branch as we need to fix this but in the lowest supported branch?

**Comment by theyough** [comment]
@malarzm , sorry i was a bit in rush, yesterday.i will do. Thank you

**Comment by theyough** [comment]
@malarzm it appears from what i see, that this bug beginning from branch 2.X

**Comment by malarzm** [comment]
@theyough the call is missing in `1.3.x` as well: https://github.com/doctrine/mongodb-odm/blob/1.3.x/lib/Doctrine/ODM/MongoDB/Tools/Console/Command/Schema/ShardCommand.php#L29

**Comment by theyough** [comment]
Yes but there is no parent::configure() method

**Comment by malarzm** [comment]
Ah sorry, my bad!

**Pull request merged**
