### PR TITLE
Added RepositoryFactory [#891]

### PR DESCRIPTION
**Pull request by hilobok**
Added RepositoryFactory in the same way as in ORM and PHPCR. It will give the ability to inject additional services or parameters into Repository.

### CODE REVIEW

**Comment by jwage** [comment]
:+1:

**Comment by atrauzzi** [comment]
Just so I understand correctly: This would make it so that I could make a RepositoryFactory subclass that uses my framework's DI to supply the resultant instance?

**Comment by malarzm** [comment]
@atrauzzi: Yes

**Comment by atrauzzi** [comment]
:tada: :balloon:

**Pull request merged**
