### PR TITLE
[WIP] Priming for mapped references

### PR DESCRIPTION
**Pull request by pvolok**
This PR addresses #319.

For now, I only implemented it for ReferenceMany. I'll add ReferenceOne support after I polish this.

Would be nice if someone who deeply understands mongodb-odm suggest how to test this feature.

### CODE REVIEW

**Comment by jwage** [comment]
Can you rebase this PR?

**Comment by pvolok** [comment]
I'll try to check this tomorrow.

**Comment by pvolok** [comment]
Hey guys. Reference priming was significantly refactored it looks like. I'm not sure that this PR makes sense anymore.

Btw, I got a `Segmentation fault: 11` error on running phpunit (osx + latest phpunit.phar).

**Comment by alcaeus** [comment]
> Btw, I got a Segmentation fault: 11 error on running phpunit (osx + latest phpunit.phar)

Same here. Couldn't track it down yet :(

**Comment by malarzm** [comment]
@pvolok @alcaeus no luck with git bisect?

**Comment by alcaeus** [comment]
@malarzm Yes, to no avail. It fails regardless of branch, so I suspect it's something with PHP version or package. I'll investigate and let you know if I find something.

**Comment by alcaeus** [comment]
@pvolok I've managed to narrow the failure down to one test - can you confirm the following?
```
$ phpunit --debug --filter testForceEnableRequireIndexes tests/Doctrine/ODM/MongoDB/Tests/Functional/RequireIndexesTest.php
PHPUnit 3.7.38 by Sebastian Bergmann.

Configuration read from /Users/abraun/Code/mongodb-odm/phpunit.xml.dist


Starting test 'Doctrine\ODM\MongoDB\Tests\Functional\RequireIndexesTest::testForceEnableRequireIndexes'.
Segmentation fault: 11
```

**Comment by pvolok** [comment]
@alcaeus Yea, same output as yours.

**Comment by malarzm** [comment]
Seems similar to #1045 since it involves requireIndexes

**Comment by pvolok** [comment]
@malarzm I get this on php 5.6

**Comment by jmikola** [comment]
This is definitely the same issue as #1045. @alcaeus: Feel free to cross-post https://github.com/doctrine/mongodb-odm/pull/656#issuecomment-88011281 over to that issue.

**Comment by alcaeus** [comment]
@pvolok Your code adds all possible elements to the collection, without respecting any ```criteria```, ```sort```, ```limit``` or ```skip``` options that can be set on the reference. That way, the collection will be pre-loaded with the wrong data.

**Comment by pvolok** [comment]
@alcaeus Maybe these props wasn't here 2 years ago when I created this PR or I just missed them. Anyway it makes this PR even more irrelevant so I'm just closing it.

**Pull request closed without merging**
