### PR TITLE
Fix links to mongodb manual

### PR DESCRIPTION
**Pull request by idetox**
|      Q       |   A
|------------- | -----------
| Type         | improvement
| BC Break     | no
| Fixed issues | 

#### Summary

Fixed links to mongodb manual

What does the PR do : 
- [x] Fix links that lead to "page not found"
- [x] Fix `http(s)://docs.mongodb.org` to `https://docs.mongodb.com`
- [x] Fix some links pointing to `/master/` to `/manual/` instead

### CODE REVIEW

**Comment by malarzm** [comment]
@idetox thank you for the PR! 2 questions:

1) could you please rebase your work on top of `2.1.x`?
2) would you mind fixing other links that point to http://docs.mongodb.org?

**Comment by idetox** [comment]
> @idetox thank you for the PR! 2 questions:
> 
> 1. ~could you please rebase your work on top of `2.1.x` (and target that branch)?~ actually nevermind, the links still work so there's no real need to include them in 2.1.x
> 2. would you mind fixing other links that point to http://docs.mongodb.org?

Sure i will do it next week!

**Comment by idetox** [comment]
@malarzm done, fixed all links to mongodb manual + updated description

**Review by SenseException — APPROVED** [review]

**Comment by SenseException** [comment]
The  Code Quality  break is unrelated to the PR

**Comment by malarzm** [comment]
@idetox awesome, thank you!

**Pull request merged**
