### PR TITLE
Use Null Coalesce Operator

### PR DESCRIPTION
**Pull request by carusogabriel**

### CODE REVIEW

**Comment by alcaeus** [comment]
As with #1691, I've tagged this for 2.0 and will merge it once #1553 has been merged down.

**Comment by alcaeus** [comment]
@carusogabriel could you rebase this pull request?

**Comment by carusogabriel** [comment]
Sure, I’ll rebase and search for similars 👨‍💻

**Comment by alcaeus** [comment]
Thanks @carusogabriel!

**Pull request merged**
