### PR TITLE
[2.0] Remove deprecated increment type

### PR DESCRIPTION
**Pull request by malarzm**
@alcaeus I think I have removed all BC stuff but I'd appreciate you having a closer look :)

### CODE REVIEW

**Comment by alcaeus** [comment]
Looks complete, apart from the `@increment` annotation class itself.

**Comment by malarzm** [comment]
Annotation is being removed in #1471 :)

**Comment by alcaeus** [comment]
Yeah, Obviously. My bad 😃

**Comment by malarzm** [comment]
Docs are now removed too

**Pull request merged**
