### PR TITLE
add test for issue #1346 public property undefined

### PR DESCRIPTION
**Pull request by zajca**
test should fail with:
```
Doctrine\ODM\MongoDB\Tests\Functional\Ticket\GH1346Test::testPublicDistanceProperty
Undefined property: Proxies\__CG__\Doctrine\ODM\MongoDB\Tests\Functional\Ticket\GH1346ReferencedDocument::$distance

/<path>/mongodb-odm/tests/Proxies/__CG__DoctrineODMMongoDBTestsFunctionalTicketGH1346ReferencedDocument.php:64
/<path>/mongodb-odm/lib/Doctrine/ODM/MongoDB/UnitOfWork.php:614
/<path>/mongodb-odm/lib/Doctrine/ODM/MongoDB/UnitOfWork.php:687
/<path>/mongodb-odm/lib/Doctrine/ODM/MongoDB/UnitOfWork.php:674
/<path>/mongodb-odm/lib/Doctrine/ODM/MongoDB/UnitOfWork.php:903
/<path>/mongodb-odm/lib/Doctrine/ODM/MongoDB/UnitOfWork.php:388
/<path>/mongodb-odm/lib/Doctrine/ODM/MongoDB/DocumentManager.php:526
/<path>/mongodb-odm/tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH1346Test.php:45

FAILURES!
Tests: 1, Assertions: 0, Errors: 1.
```

### CODE REVIEW

**Comment by malarzm** [comment]
Oh right, now that we have a failing test case could you make it as small as possible to still fail? It really helps after some time if it'd start failing again. For instance there's no need to remove documents explicitly as `BaseTest` drops collections anyway or having `Index` probably doesn't bring any value to the test itself

**Comment by zajca** [comment]
Test should be now simple as possible. I didn't success to replicate this with less calls.

**Comment by malarzm** [comment]
Awesome this will be enough :) I personally won't be able to investigate this before weekend but if you or anyone else would like to take a stab and need help please feel free to ping me either here or on IRC

**Comment by malarzm** [comment]
#1355 included provided test and has been merged

**Pull request closed without merging**
