### PR TITLE
Add PHPStan

### LINKED ISSUE #1701: [2.0] Add PHPStan
From the documentation: 
> [PHPStan](https://github.com/phpstan/phpstan) focuses on finding errors in your code without actually running it. It catches whole classes of bugs even before you write tests for the code.

### PR DESCRIPTION
**Pull request by carusogabriel**
This starts #1701 by adding `PHPStan` :man_technologist:

### CODE REVIEW

**Comment by carusogabriel** [comment]
Sounds like a lot of tests will have to be namespaced and type hinting fixed to fix level 0

**Comment by malarzm** [comment]
@carusogabriel I wouldn't worry about `tests` folder at all, just the `lib` :)

**Comment by carusogabriel** [comment]
2b6996e was made based on [PHP Manual](http://php.net/manual/pt_BR/mongo.types.php)

**Comment by carusogabriel** [comment]
@malarzm Just to remain errors to go for level 2 that I couldn't figure out:
```bash
 ------ ----------------------------------------------------------- 
  Line   lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php  
 ------ ----------------------------------------------------------- 
  291    Caught class MongoException not found.                     
  356    Caught class MongoCursorException not found.               
 ------ ----------------------------------------------------------- 
```

**Comment by malarzm** [comment]
These are [from the old driver](http://php.net/manual/pl/class.mongoexception.php) :)

**Comment by malarzm** [comment]
I guess they could be replaced with `MongoDB\Driver\Exception\RuntimeException` but I'd rather defer this to decision to @alcaeus or @jmikola as they know way more about new driver than I do

**Comment by alcaeus** [comment]
> I guess they could be replaced with `MongoDB\Driver\Exception\RuntimeException`

Almost correct - we can narrow that down to `MongoDB\Driver\Exception\WriteException`.

**Comment by carusogabriel** [comment]
For level 2, we have a common situation:
```
public function method (/** $var */) {
}
```
And the PHPStan error:
```
PHPDoc tag @param references unknown parameter $var
```
How should we deal with?

**Comment by alcaeus** [comment]
I'm not sure what you mean - can you link a concrete example?

**Comment by carusogabriel** [comment]
The PHPStan error: https://travis-ci.org/doctrine/mongodb-odm/jobs/326700321#L1584
The `geoWithinPolygon` method at `lib/Doctrine/ODM/MongoDB/Query/Expr.php`: https://github.com/doctrine/mongodb-odm/blob/master/lib/Doctrine/ODM/MongoDB/Query/Expr.php#L595

**Comment by alcaeus** [comment]
Ah, gotcha. These probably should be converted to proper variadic args. I'll leave it up to you whether you want to take care of that in this PR or do it in a separate one.

**Comment by carusogabriel** [comment]
Ok. I'll correct the easy ones first, them figure out these :+1:

**Comment by malarzm** [comment]
@carusogabriel I've merged most of removals for 2.0 and should be done with them for good later today - you'll need to rebase your branch then as conflicts are already popping up

**Comment by carusogabriel** [comment]
@malarzm Ok, I’ll wait to continue with fixes 👍

**Comment by malarzm** [comment]
All right @carusogabriel all my recent PRs are meged now, please rebase :)

**Comment by alcaeus** [comment]
@carusogabriel regarding variadic arguments, I've stumbled over them while working on #1702 and fixing checkstyle violations. There are quite a few method signatures that can be fixed, so I'll create a separate pull request for them.

**Comment by carusogabriel** [comment]
@alcaeus Perfect, this will reduce the number of errors. The remains are about annotations and probably `__call()` methods, something that I'm still [learning in `PHPStan`](https://github.com/phpstan/phpstan#extensibility). I let you know if got stuck :grimacing:

**Comment by Majkl578** [comment]
@carusogabriel most of them look like typehinting errors regarding ClassMetadata vs. ClassMetadataInfo, likely something inherited from ORM back then (which ORM now tries to exterminate: doctrine/doctrine2#6886). Feel free to ping me on Slack if you need any advice with PHPStan. The higher level the better (at least 5-6 + [extra strict rules](https://github.com/phpstan/phpstan-strict-rules) would be decent). :)

**Comment by carusogabriel** [comment]
@Majkl578 Let me see if I understand: We should no longer use `ClassMetadataInfo`. Instead, use `ClassMetadata`? 
Example: the `AnnotationDriver` class, on method `loadMetadataForClass` uses `ClassMetadata`. But, the following line uses `ClassMetadataInfo`. Changing it does not affect anything :cry: 

https://github.com/doctrine/mongodb-odm/blob/fb9b49291c1be91d0afd2406e371558d3d51299e/lib/Doctrine/ODM/MongoDB/Mapping/Driver/AnnotationDriver.php#L33-L36

**Comment by alcaeus** [comment]
`ClassMetadata` and `ClassMetadataInfo` should be combined, yes.

**Comment by carusogabriel** [comment]
@alcaeus by `ClassMetadata` and `ClassMetadataInfo` you mean our `Doctrine\ODM\MongoDB\Mapping\ClassMetadata` and `Doctrine\ODM\MongoDB\Mapping\ClassMetadataInfo`?

**Comment by alcaeus** [comment]
Sorry, yes 👍

**Comment by carusogabriel** [comment]
@alcaeus @malarzm May I ask you to continue with this? I don't know the library well to continue this work :disappointed: 

I've rebased and stopped at level 1.

**Comment by alcaeus** [comment]
@carusogabriel sure! Just to know where we stand, is level 1 complete? If so, I'd say we merge this and then continue in separate pull requests. If level 1 doesn't pass, I'd argue to return CI to level 0 to have a green build and merge the pull request afterwards.

**Comment by carusogabriel** [comment]
@alcaeus Rebased, Level 1 passing and added to Travis CI :white_check_mark:

**Comment by alcaeus** [comment]
That sounds good, build is also passing. I'll review this later today.

**Comment by alcaeus** [comment]
Thanks @carusogabriel!

**Pull request merged**
