### PR TITLE
Fix the ' needs an Object' exception for simple references

### PR DESCRIPTION
**Pull request by coudenysj**
Bug discovered in #1349 and planned to be solved in #1405, but created this fix for the 1.0.x branch first.

### CODE REVIEW

**Comment by coudenysj** [comment]
@alcaeus Is there a way to start the build again without pushing a dummy commit?

**Comment by alcaeus** [comment]
> Is there a way to start the build again without pushing a dummy commit?

Not sure if you can do it yourself but I just restarted the failing build.

**Comment by coudenysj** [comment]
Thanks. Looks like everything is working now.

Do I need to create a pull request for master, or will you do that manually?

**Comment by alcaeus** [comment]
I'll merge it down after merging it into 1.0 - should get to it either tonight or no later than tomorrow. Thanks for your effort! 👍

**Pull request merged**
