### PR TITLE
UnitOfWork cleanup

### PR DESCRIPTION
**Pull request by malarzm**

### CODE REVIEW

**Comment by jmikola** [comment]
You and @jwage are absolutely sure that CommitOrderCalculator is obsolete? :smile:

**Comment by jwage** [comment]
We don't need it, but just noting that without it, the order in which documents are inserted and updated will change. This order could be an assumption that someone is relying on.

**Comment by malarzm** [comment]
That assumption was very dangerous given that there could be more than one valid commit order :)

**Comment by malarzm** [comment]
Merged manually in https://github.com/doctrine/mongodb-odm/commit/9addf539dfbdbe83799abbf90f70503eb36ef3e3

**Pull request closed without merging**
