### PR TITLE
Fix detach cascading see #978 

### PR DESCRIPTION
**Pull request by fridolin-koch**
As described in #978 I think the detach cascading for embedded documents is not working correct. I also added  a small test.

I was not sure where to put the test.. I hope it is correct this way.

### CODE REVIEW

**Comment by malarzm** [comment]
This has been merged manually in https://github.com/doctrine/mongodb-odm/commit/994783a5edfd5f2cbe29f709cf49cbb5ad40ccb7 - thanks @fridolin-koch!

**Comment by jmikola** [comment]
@fridolin-koch, @malarzm: Comparable logic existed in `cascadeRefresh()`, which recurses with `cascadeRefresh()` instead of `doRefresh()` on the embedded document(s). I suppose that's alright since embedded documents would never be refreshed on their own (unlike detachment). Would you agree?

**Comment by malarzm** [comment]
I agree with that :)

**Comment by fridolin-koch** [comment]
I also agree :+1:

**Pull request closed without merging**
