### PR TITLE
ReferenceMany: insert an empty array

### PR DESCRIPTION
**Pull request by ajax13**
Related to #1195

### CODE REVIEW

**Comment by malarzm** [comment]
@ajax13 thanks for the PR! We require though that each change has a corresponding test so there will be no regressions in the future. Also I'm afraid that simply putting empty arrays after years of not doing anything will be a BC break for people looking for no existing field through query builder... thoughts on this @alcaeus @jmikola?

**Comment by jmikola** [comment]
> Also I'm afraid that simply putting empty arrays after years of not doing anything will be a BC break for people looking for not existing field through query builder...

I think a BC-friendly approach would be having an option on the EmbedMany or ReferenceMany option that allows an empty array to be created if the collection is empty (instead of leaving the field omitted).

If I had to guess, the current behavior of omitting empty collections is related to [`@Field`](http://docs.doctrine-project.org/projects/doctrine-mongodb-odm/en/latest/reference/annotations-reference.html#field) and `nullable` (by default, fields with `null` values are unset in the document).

Otherwise, this seems like something you might simply change in 2.0 and document in the release notes.

**Comment by alcaeus** [comment]
> I think a BC-friendly approach would be having an option on the EmbedMany or ReferenceMany option that allows an empty array to be created if the collection is empty

I agree on this and I also agree on using `nullable`, with the only difference that we wouldn't store `null` but rather `[]` (or `{}` if using `set` or `atomicSet` strategies).

**Comment by malarzm** [comment]
Putting into 2.0 bucket

**Comment by spiider8** [comment]
Hi, will be this funkcionality merged sometime pls?

**Comment by malarzm** [comment]
We can't merge the PR as-is, it requires more work. Somebody interested needs to pick it up

**Comment by khaperets** [comment]
> Hi, will be this funkcionality merged sometime pls?

I hope someone fixes it

**Comment by malarzm** [comment]
Superseded by #2547

**Pull request closed without merging**
