### PR TITLE
Fix PersistentCollection init state during flush()

### LINKED ISSUE #921: ReferenceMany Collection after flush
After a flush (in the same request), the count of the ReferenceMany Collection give the right count, but if we "foreach" we have the first collection data that the repository give.

```
<?php
/**
 * @ODM\Document
 */
class User
{
    /**
     * @ODM\id
     */
    private $id;

    /**
     * @ODM\String
     */
    private $name;

    public function setName($name)
    {
        $this->name = $name;
        return $this;
    }

    public function getName($name)
    {
        return $this->name;
    }

    /**
     * @ODM\ReferenceMany(targetDocument="Post")
     */
    private $posts;

    public function __construct()
    {
        $this->posts = array();
    }

    public function addPost(Post $post)
    {
        $this->posts[] = $post;
    }

    public function getPosts()
    {
        return $this->posts;
    }
}


/**
 * @ODM\Document
 */
class Post
{
    /**
     * @ODM\id
     */
    private $id;

    /**
     * @ODM\ReferenceOne(targetDocument="User")
     */
    private $user;

    public function setUser($user)
    {
        $this->user = $user;
    }

}




$user = $dm->getRepository('User')->findOneByName('smith');

$post = new Post();
$dm->persist($post);

$user->addPost($post);

$dm->persist($user);
$dm->flush();



var_dump(count($user->getPosts()));
foreach ($user->getPosts() as $post) {
    var_dump('POST');
}

$dm->refresh($user);
var_dump(count($user->getPosts()));
foreach ($user->getPosts() as $post) {
    var_dump('POST');
}
```

Output

```
int(1)
int(1)
POST
```

### LINKED ISSUE #963: PersistentCollection count, isDirty and initialize
Hi there,
I'm doing the following:
1. Adding an object to PersistentCollection
2. Saving PersistentCollection
3. Attempting to get the object out of the PersistentCollection

What I find is that `$this->pColl->count()` is returning 1, which is what I expect. Note `count()` does not call `initialize()`.

When I call `toArray()` `initialize()` is called and the `isDirty` is false, so the collection is cleared and the object I added is lost. I get zero members back and now `count()` is zero.

The PersistentCollection is being saved to the DB.

I'm using the latest "dev-master".

Any help is appreciated.
Thanks.

### PR DESCRIPTION
**Pull request by malarzm**
Fixes #921 
EDIT: Fixes #963 as well

### CODE REVIEW

**Comment by rubenrua** [comment]
+1

**Comment by jmikola** [comment]
Manually merged in https://github.com/doctrine/mongodb-odm/commit/b00177ce241214cfaf2eb2a01885d964a55a8ed8.

@rubenrua: I ended up replacing your test case, as I already had a test with more coverage back from when #921 was originally reported. Nevertheless, thanks for the effort on that.

@malarzm: I also reverted the removal of setting `isDirty` from https://github.com/doctrine/mongodb-odm/commit/bd573cb7def6ab22df8c465b0d79003d26e28046 and added a test for `isDirty` is preserved. That was the only functional change from that original commit, and although it doesn't seem to have caused #921 and #963 on its own (based on some quick testing), removing it was an error on my part. Thanks very much for resolving this.

**Comment by malarzm** [comment]
:+1:

**Comment by rubenrua** [comment]
@jmikola I updated my test with a bi-directional reference and it's broken again.

See: https://github.com/doctrine/mongodb-odm/pull/1014

**Pull request closed without merging**
