### PR TITLE
[WIP] Strict Mode for QueryBuilder

### PR DESCRIPTION
**Pull request by malarzm**
Implementation for feature proposed in https://github.com/doctrine/mongodb-odm/issues/866 Any suggestions of what else should be tested are more than welcome

Checklist:
- [x] simple fields and simple fields in EmbedOne/ReferenceOne documents
- [ ] tests with EmbedMany, ReferenceOne, $elemMatch
- [ ] tests with discriminators
- [x] test with different field and fieldName
- [x] "Have you meant" in Exception
- [ ] Docs

### CODE REVIEW

**Comment by malarzm** [comment]
Closing since most probably I will not get back to working on this feature

**Comment by st0at** [comment]
So why was this pull request closed? This is very needed feature.

**Comment by malarzm** [comment]
There were more important things to do at a time. Plus I've realized what a headache embeddables and discriminators will bring :)

**Comment by st0at** [comment]
Yes, I fully understand you :)

**Pull request closed without merging**
