### PR TITLE
Clean elses

### PR DESCRIPTION
**Pull request by carusogabriel**
I've removed the `else`s when we have already returned something :put_litter_in_its_place:

### CODE REVIEW

**Comment by malarzm** [comment]
As this overlaps with what's happening right now in `odm-ng` branch (I think) I'm leaving the merge decision up to @alcaeus :)

**Comment by carusogabriel** [comment]
Didn't know that was a branch for next version development already :sweat_smile:

**Comment by malarzm** [comment]
There's that big https://github.com/doctrine/mongodb-odm/pull/1553 that switches us to the new driver and moves all relevant things (including query/aggregation builders) from `doctrine/mongodb` into the ODM :)

**Comment by alcaeus** [comment]
I've tagged this for the 2.0 milestone and will take a look once #1553 has been merged down. I'll try to get that done within a week or so, after that improvement PRs such as this can be based on odm-ng (or master if I can finally push myself to just merge odm-ng down).

**Comment by alcaeus** [comment]
@carusogabriel could you rebase this pull request?

**Comment by carusogabriel** [comment]
Sure, I’ll rebase and search for similars 👨‍💻

**Comment by carusogabriel** [comment]
@alcaeus Only one test failed because of `Mongo`. Should we retrigger it?

**Comment by alcaeus** [comment]
Done.

**Comment by alcaeus** [comment]
Thanks @carusogabriel!

**Pull request merged**
