### PR TITLE
Add support for custom object ids (#1178)

### PR DESCRIPTION
**Pull request by marcospassos**
This PR adds support for custom object IDs #1178.

### CODE REVIEW

**Comment by malarzm** [comment]
@marcospassos few things :)

1. Bunch of newlines are missing at the end of files
2. Would be cool to add a test with custom type, similar as you gisted in #1178
3. Somehow there are conflicts, could you rebase?

**Comment by malarzm** [comment]
Also to cross reference with #1179, it would be great if you could include some functional tests for `Query\Builder:references`, finding by id with `Repository` etc

**Comment by marcospassos** [comment]
Could you please explain it a bit more in depth?

**Comment by marcospassos** [comment]
*Snippet of use cases would be really helpful

**Comment by malarzm** [comment]
> Snippet of use cases would be really helpful

`$repository->findOne($userId)` 

or 

```
// $user has custom id and $log holds Reference to User
$log->setUser($user);
$dm->persist($log);
$dm->flush();
// Query\Builder for Log
$qb->find()->field('user')->references($user)->execute();
// did it fetch things correctly?
```

**Pull request closed without merging**
