### PR TITLE
Use PHPUnit 10

### LINKED ISSUE #2509: Ensure PHPUnit 10 compatibility
This is to track PHPUnit 10 compatibility with the test suite:

- [x] Rename abstract test classes ending with `Test` #2507 
- [x] Make all data providers static
- [x] Replace usages of deprecated and deleted test methods
- [x] Migrate XML configuration
- [x] Get rid of deprecations in tests

### PR DESCRIPTION
**Pull request by franmomu**
Closes https://github.com/doctrine/mongodb-odm/issues/2509

Since we are using PHP 8.1, we don't need PHPUnit 9 anymore, I've installed [rector](https://github.com/rectorphp/rector) locally and replaced annotations with attributes.

### CODE REVIEW

**Comment by malarzm** [comment]
I'm surprised so little had to be done :) One thing that is off though is number of tests executed:

[This PR's PHP 8.1, Server 6.0, highest](https://github.com/doctrine/mongodb-odm/actions/runs/6682221897/job/18157197022?pr=2564#logs) executed 2646 tests
[2.6.x's counterpart](https://github.com/doctrine/mongodb-odm/actions/runs/6678934179/job/18150508347) has 2467 tests

Am i looking correctly that there is a test that got lost somewhere?

**Comment by malarzm** [comment]
Actually there's a chance that PHPUnit's deprecation was counted towards number of tests:

```
There was 1 PHPUnit test runner deprecation:

1) Your XML configuration validates against a deprecated schema. Migrate your XML configuration using "--migrate-configuration"!
```

but that be weird decision from PHPUnit's team

**Review by malarzm — APPROVED** [review]
@franmomu feel free to merge once you decide whether my previous comment makes sense or no :)

**Comment by franmomu** [comment]
> I'm surprised so little had to be done :) One thing that is off though is number of tests executed:
> 
> [This PR's PHP 8.1, Server 6.0, highest](https://github.com/doctrine/mongodb-odm/actions/runs/6682221897/job/18157197022?pr=2564#logs) executed 2646 tests [2.6.x's counterpart](https://github.com/doctrine/mongodb-odm/actions/runs/6678934179/job/18150508347) has 2467 tests
> 
> Am i looking correctly that there is a test that got lost somewhere?

Good catch! it was my fault in https://github.com/doctrine/mongodb-odm/pull/2564/files#diff-62b86ab419dbc39877816e5c1f489b8fa4110e14bb395c2ba9f7cd961720ef60L13-L17

```php
    /**
     * @testWith ["groups"]
     *           ["groupsSimple"]
     */
```
was changed to 

```php
    #[TestWith(['groups', 'groupsSimple'])]
```

instead of 

```php
    #[TestWith(['groups'])]
    #[TestWith(['groupsSimple'])]
```

**Pull request merged**
