### PR TITLE
Undelete embedded document during change set calculation if needed

### PR DESCRIPTION
**Pull request by malarzm**
Fixes #1225 

@blockjon can you see if my fix to UnitOfWork will fix your code as well?

### CODE REVIEW

**Comment by blockjon** [comment]
@malarzm Thanks for this. I should be able to get this verified by tomorrow.

**Comment by malarzm** [comment]
@blockjon got any news for me? :)

**Comment by alcaeus** [comment]
Superseded by #1248.

**Comment by blockjon** [comment]
@malarzm I'm sorry I didn't respond to this I lost track of things. If the functional test I submitted passes then I'm sure it would fix the problem I encountered.

**Pull request closed without merging**
