### PR TITLE
Drop support for MongoDB 4.4

### PR DESCRIPTION
**Pull request by malarzm**
MongoDB 4.4 reached its EOL in February so let's make the CI lighter for upcoming version

### CODE REVIEW

**Comment by SenseException** [comment]
If 4.4 gets dropped, does it make sense to have older versions mentioned in the docs? At this point multi-document transactions are a given.
https://github.com/doctrine/mongodb-odm/blob/2.8.x/docs/en/reference/transactions-and-concurrency.rst?plain=1#L18-L19

**Comment by malarzm** [comment]
Good catch! It does not. Github did not showed me those when grepping for `4.4` with UI. Will adjust it later :)

**Review by SenseException — APPROVED** [review]

**Comment by GromNaN** [comment]
For the record, even if the server is no longer supported in version 4.4, we continue to maintain the driver for 3 years from the server version EOL.

**Review by GromNaN — APPROVED** [review]

**Comment by malarzm** [comment]
> For the record, even if the server is no longer supported in version 4.4, we continue to maintain the driver for 3 years from the server version EOL.

Luckily enough no code paths were made, so technically 4.4 still works with ODM. We're just not testing against it which I think is fair given it has reached EOL :)

I'll be merging this PR as CI fails are not related.

**Comment by malarzm** [comment]
Dang, I've missed some 5.0 sharded cluster fail. That's what one gets from a broken CI :( I'll be looking into it

**Pull request merged**
