### PR TITLE
Throw exception for targetDocument & discriminatorMap field mapping

### PR DESCRIPTION
**Pull request by Steveb-p**
|      Q       |   A
|------------- | -----------
| Type         | improvement
| BC Break     | no
| Fixed issues | #2203

#### Summary

Throws an exception when `discriminatorMap` is used alongside with `targetDocument`.

When used together their behavior was to discard object different than `targetDocument` specified, which lead to potential data loss.

I'm not sure about the tests, or placement of functions / checks, so correct me please :smiley_cat:

### CODE REVIEW

**Comment by malarzm** [comment]
I'm adding this to 1.3.8 milestone as the original issue so stalebot will leave this PR be while we wait for resolution

**Comment by alcaeus** [comment]
Sorry for the delay here, this totally slipped under my radar. Typically, we'd fix this in 2.1 as that's the current bug fix version. The only concern I have about the patch is that it would start throwing exceptions in code that worked "fine" before. "Fine" meaning that it would store data and ignore the discriminator map. Due to this, we may want to add a deprecation warning about this in 2.2 and only throw an exception about this invalid use-case in 3.0. What do you think @Steveb-p @malarzm?

**Comment by malarzm** [comment]
I'm on board 👍

**Comment by Steveb-p** [comment]
@alcaeus the reason I considered this important enough to throw an exception is that it I think it resulted in some data loss for sometime ago.

I don't remember the original issue in the application I've worked on that caused me to notice this, so I'm not really sure now.

Of course, I absolutely understand that due to the fact that this changes the behavior of the lib in a particular case it should wait for a major release. It's just that weighting data loss against BC break lead me to prefer the exception at that point.

**Comment by alcaeus** [comment]
@Steveb-p agree - the prospect of potential data loss is something I considered as well, but I'm not sure that potentially breaking something that may just have worked (including in our own tests) is worth it. We could lock this down a bit in the validation command to point out that the mapping is invalid and only throw a deprecation for the time being. We can then always decide to accept the BC break if we realise that this causes significant problems for people. We'll include one or the other in 2.2 - I just quite haven't made up my mind yet.

**Comment by alcaeus** [comment]
@Steveb-p I've taken your work and changed it to only emit a deprecation notice, see #2271. I'm hesitant to make this an exception right away, so I feel deprecating this at least gives people that are affected some pause to think about what they're doing.

On a different note, I noticed that the tests you added only check for an exception, which was still happening despite removing the `throw` statement you added: this was because the mapping was invalid to begin with due to a missing `fieldName` field.

**Pull request closed without merging**
