### PR TITLE
[wip] added serialized type

### PR DESCRIPTION
**Pull request by ruslan-polutsygan**
It fixes issue https://github.com/doctrine/mongodb-odm/issues/687

If it looks OK for you, I'll add tests.

### CODE REVIEW

**Comment by jwage** [comment]
I don't think we should be storing serialized PHP data in mongodb. It should be able to store any arbitrary array structure so storing it natively should not be a problem.

**Comment by makasim** [comment]
There is still a problem, I have an object which is stored in a document's property and I do not want to use embedable to store it, It is just overkill in my situation. I just want  it to be serialized and stored. That's it. Without this the library limits me which is bad. It pushes me to create one more document define its schema use it as embedable. I dont need all that stuff. IMO the library should provide different ways to solve problems and I have to choose a better solution for my case. 

And the other point: There is an inconsistency between Doctrine ORM and ODM. ORM provide such a feature but ODM does not.

**Comment by makasim** [comment]
To be more concret:

Here's the document: https://github.com/Payum/Payum/blob/master/src/Payum/Core/Model/Token.php#L13

and this object https://github.com/Payum/Payum/blob/master/src/Payum/Core/Model/Identity.php I want to serialize in details property. 

Here's the currenct schema I use https://github.com/Payum/Payum/blob/master/src/Payum/Core/Bridge/Doctrine/Resources/mapping/Token.mongodb.xml#L11 

and to make it work I ask users to register a custom type ObjectType.

**Comment by makasim** [comment]
@jwage ping

**Comment by smolinari** [comment]
I am admittedly quite new to all this, but I am also not getting the reasoning for this. What overhead/ overkill are you talking about, when working with an embedded document (your object?)? How is that a limit? Instead of working with "details" as a special field type, you could simply embed your Identity object directly, couldn't you? 

`/** @Document */
class Token implements TokenInterface
{
    // ...

    /** @EmbedOne(targetDocument="Identity") */
    private $details;

    // ...
}

/** @EmbeddedDocument */
class Identity extends IdentityInterface
{
    // ...
}`

Isn't this possible?

Scott

**Pull request closed without merging**
