### PR TITLE
Add tests directory to phpstan

### PR DESCRIPTION
**Pull request by franmomu**
To see the errors, after https://github.com/doctrine/mongodb-odm/pull/2311 there should be way less.

### CODE REVIEW

**Comment by alcaeus** [comment]
@franmomu What do you think about generating a baseline for the tests directory, document how to update this baseline, and defer fixing these to future pull requests? I believe enforcing stricter rules for new code makes sense, and might also help with fixing some existing failures. If so, I'm fine merging this PR with a baseline.

**Comment by franmomu** [comment]
> @franmomu What do you think about generating a baseline for the tests directory, document how to update this baseline, and defer fixing these to future pull requests? I believe enforcing stricter rules for new code makes sense, and might also help with fixing some existing failures. If so, I'm fine merging this PR with a baseline.

Yeah sure, let's wait for https://github.com/doctrine/mongodb-odm/pull/2311 to be merged so the baseline would be quite smaller.

**Comment by alcaeus** [comment]
> Yeah sure, let's wait for #2311 to be merged so the baseline would be quite smaller.

Done! 👍

**Review by alcaeus — APPROVED** [review]

**Comment by alcaeus** [comment]
Thanks @franmomu!

**Pull request merged**
