### PR TITLE
Use createMock where possible

### PR DESCRIPTION
**Pull request by malarzm**
as `getMock` was deprecated. As a bonus I changed now unnecessary long `getMockBuilder` to `createMock` too

### CODE REVIEW

**Comment by alcaeus** [comment]
Looks good, although I think this needs to go into the 1.0 branch to avoid large code differences which might make merging harder. After all, we're supporting that until December 😉

**Comment by malarzm** [comment]
Ack, wasn't sure which way to go, will rebase this tomorrow ;)

**Comment by malarzm** [comment]
Turns out I can't backport this into `1.0.x` because PHP version is too low for new phpunit to be installed (see [travis build](https://travis-ci.org/doctrine/mongodb-odm/builds/147722522) for #1464)

**Comment by alcaeus** [comment]
Fair enough 👍

**Comment by coudenysj** [comment]
@malarzm What version of PHPUnit is required for this? I want to start a new branch from "odm-ng", but cannot get phpunit to finish:

```
vagrant@jessie:~$ vendor/bin/phpunit
PHPUnit 5.2.12 by Sebastian Bergmann and contributors.

..........................PHP Fatal error:  Call to undefined method Doctrine\ODM\MongoDB\Tests\DocumentManagerTest::createMock() in /vagrant/tests/Doctrine/ODM/MongoDB/Tests/DocumentManagerTest.php on line 233

vagrant@jessie:~$ php -v
PHP 5.6.24-0+deb8u1 (cli) (built: Jul 26 2016 08:17:07)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
```

**Comment by malarzm** [comment]
I see that on travis it picked up `5.4.8` and I indeed might forgot to update `composer.json` for this :)

**Comment by malarzm** [comment]
@coudenysj yup, it was instroduced in 5.4 - https://github.com/sebastianbergmann/phpunit/blob/d1e1d73a5a49e8f963572a46058da2e56d30566d/ChangeLog-5.4.md#added

**Pull request merged**
