### PR TITLE
Align phpdoc

### PR DESCRIPTION
**Pull request by malukenho**

### CODE REVIEW

**Comment by alcaeus** [comment]
If you look closely you will see that everything below this line is indented 5 characters instead of 4. Note sure we want to change this as it will make merging existing pull requests that change UoW below this line a real pain. Thoughts, @malarzm and @jmikola?

**Comment by malukenho** [comment]
@alcaeus I guess old PR's can be rebased.

**Comment by alcaeus** [comment]
I apologise, apparently my IDE tricked me into thinking indentation is wrong. You are correct, the comment line is the only one that is incorrect. :+1:

**Comment by malukenho** [comment]
@alcaeus thanks :D

**Comment by alcaeus** [comment]
Thanks!

**Pull request merged**
