### PR TITLE
Version bugfix

### PR DESCRIPTION
**Pull request by jaymecd**
This PR provided:

- [x] missing xml driver mapping for version/lock
- [x] set initial version if document is saved in upsert mode
- [x] write tests

### CODE REVIEW

**Comment by jaymecd** [comment]
@jmikola, could u give some advice how to provide better tests for this fix? tnx

**Comment by jmikola** [comment]
@jaymecd: I believe the only tests for versions and locking is in `LockTest.php`. You appear to be fixing two code paths in this PR (insert and upsert).

Your fix for insert is initializing an empty (zero when cast to an integer) `$version` property. For that, you should be able to trigger the bug by changing the following in `LockTest.php`:

```php
/** @ODM\Document */
class LockInt extends AbstractVersionBase
{
    /** @ODM\Version @ODM\Int */
    public $version = 1;
}
```

The upsert path is ultimatey decided in `UnitOfWork::persistNew()` when we examine the persisted document. If it contains a value in its `$id` field, we'll upsert it. Since all of the properties in the `LockTest.php` models are public, it should be easy to add some new tests there which set `$id` to a new MongoId before persisting (i.e. generating the ObjectId yourself instead of letting ODM do it).

**Comment by jaymecd** [comment]
@jmikola done + updated xml driver mapping test for version

**Comment by jmikola** [comment]
Merged in https://github.com/doctrine/mongodb-odm/commit/b37c4c3dd913d707c743e78e15c39e5dbba2f193.

In the future, feel free to leave the commits split if it makes logical sense. I'm not sure if you rebased this, but the bug fix for initializing on upsert and XML metadata support could have been separated.

In any event, thanks!

**Pull request closed without merging**
