### PR TITLE
[2.0] Use storeAs=dbRef as the new default setting for references

### PR DESCRIPTION
**Pull request by coudenysj**
As suggested in 30285e4ba603a, the recommended setting of `storeAs=dbRef` will become the default setting in 2.0.

@malarzm I had to update my composer.json locally to be able to run phpunit (see #1463).

### CODE REVIEW

**Comment by malarzm** [comment]
@coudenysj thanks for the PR! Overally looks good, you have some places with commented out code in the tests though, I think you wanted to remove them? :)

About the `phpunit` thing, thanks for reminding me once again, duly noted to change that finally.

**Comment by coudenysj** [comment]
@malarzm The commented assertions are because I was not sure if I should remove the assertions or change the mapping information. I think I'll go with removing the assertions.

**Comment by malarzm** [comment]
@coudenysj would you mind rebasing this atop current `odm-ng` branch?

**Comment by coudenysj** [comment]
@malarzm done

**Comment by malarzm** [comment]
@coudenysj I think something went wrong as PR still has 11 commits instead of 2 you've made :)

**Comment by malarzm** [comment]
Also if you could squash these two that would allow me to push the green button instead of doing the merge manually ;)

**Comment by coudenysj** [comment]
The rebase was corrected, can't you merge pull requests with multiple commits?

**Comment by malarzm** [comment]
I can (and often I do) but the 2nd commit doesn't bring anything to the history so there's no point in having it :)

**Comment by coudenysj** [comment]
Correct. Done!

**Comment by malarzm** [comment]
Thank you! \o/

**Pull request merged**
